#!/bin/sh

## ==============================================================================
##
##  Function definitions
##
## ==============================================================================

##_______________________________________________________________________________
## Installation of MacPorts itself

install_macports ()
{
    ## Set basic variables required
    varMacPortsVersion=2.1.2
    varMacPortsArchive=MacPorts-${varMacPortsVersion}.tar.gz
    varMacPortsURL=https://distfiles.macports.org/MacPorts/$varMacPortsArchive
    
    ## Get the source code
    curl $varMacPortsURL -o ${varMacPortsArchive} -#

    ## Unpack the source file
    tar -xvzf $varMacPortsArchive

    ## Configure, build and install MacPorts
    cd MacPorts-$varMacPortsVersion
    ./configure && make && sudo make install

    ## Update configuration of MacPorts
    sudo port -v selfupdate
}

##_______________________________________________________________________________
## Remove MacPorts from the system, removing all files

uninstall_macports ()
{
    ## Uninstall all the installed ports
    sudo port -fp uninstall --follow-dependents installed

    ## Clean up directories used by MacPorts
    sudo rm -rf /opt/local
    sudo rm -rf /Applications/DarwinPorts
    sudo rm -rf /Applications/MacPorts
    sudo rm -rf /Library/LaunchDaemons/org.macports.*
    sudo rm -rf /Library/Receipts/DarwinPorts*.pkg
    sudo rm -rf /Library/Receipts/MacPorts*.pkg
    sudo rm -rf /Library/StartupItems/DarwinPortsStartup
    sudo rm -rf /Library/Tcl/darwinports1.0
    sudo rm -rf /Library/Tcl/macports1.0
    sudo rm -rf ~/.macports
}

##_______________________________________________________________________________
## Installation of basic ports

install_ports ()
{
    port install curl +ssl
    port install dvdauthor
    port install gnuplot +luaterm+pangocairo
    port install hdf5-18
    port install jpeg
    port install kde4-baseapps kdemultimedia4 libksane taglib
    port install mplayer-devel
    port install pgplot +gcc44
    port install plplot +aquaterm
    port install silo +hdf5
    port install task +bash_completion
    port install texlive +full
    port install wget +ssl
    
    sudo launchctl load -w /Library/LaunchDaemons/org.freedesktop.dbus-system.plist
}

## ==============================================================================
##
##  Main command sequence of the script
##
## ==============================================================================

install_ports
