#!/bin/sh

## ==============================================================================
##
##  Settings
##
## ==============================================================================

varMacPortsVersion=2.2.1
varMacPortsArchive=MacPorts-${varMacPortsVersion}.tar.gz
varMacPortsURL=https://distfiles.macports.org/MacPorts/${varMacPortsArchive}

## ==============================================================================
##
##  Function definitions
##
## ==============================================================================

##_______________________________________________________________________________
## Installation of MacPorts itself

install_macports ()
{
    ## Get the source code
    curl $varMacPortsURL -o ${varMacPortsArchive} -#

    ## Unpack the source file
    tar -xvzf $varMacPortsArchive

    ## Configure, build and install MacPorts
    cd MacPorts-$varMacPortsVersion
    ./configure && make && sudo make install

    ## Update configuration of MacPorts
    sudo port -v selfupdate
}

##_______________________________________________________________________________
## Installation of basic ports

install_ports ()
{
    port install curl +ssl
    port install dvdauthor
    port install gnuplot +luaterm+pangocairo
    port install hdf5-18
    port install jpeg
    port install kde4-baseapps kdemultimedia4 libksane taglib
    port install mplayer-devel
    port install pgplot +gcc44
    port install plplot +aquaterm
    port install silo +hdf5
    port install task +bash_completion
    port install texlive +full
    port install wget +ssl

    sudo launchctl load -w /Library/LaunchDaemons/org.freedesktop.dbus-system.plist
}

##===============================================================================
##
##  Command line options
##
##===============================================================================

case $1 in
    install)
        uninstall_macports
        ;;
    *)
        echo "This script has been depricated - plase use 'make update' instead."
        ;;
esac
